[package]
name = "yakou"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anstyle = "1.0.6"
cranelift = "0.105.2"
ilog = "1.0.1"
lazy_static = "1.4.0"
linked-hash-map = "0.5.6"
rand = "0.8.5"
